env: macf

env_args:
  map_name: "macf_opt"
  seed: null
  n_agents: 2

test_greedy: True
test_nepisode: 5
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2010000